package com.example.demo.service;

import com.alibaba.fastjson.JSONObject;
import com.example.demo.utils.AesUtil;
import com.example.demo.utils.ApiPostUtil;
import com.example.demo.utils.GzipUtils;
import org.junit.jupiter.api.Test;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * Created by BF100269 on 2016/10/9.
 * 身份证认证(两要素不返照片)
 */
public class AndroidDevice{
//    String url = "https://dfp.xinyan.com/gateway/device-engine-client/android/v1/gather";     //MOCK测试
//String url = "http://10.1.60.44:8102/android/v1/gather";     //MOCK测试
String url = "https://10.0.21.74:8901/gateway/device-engine-client/android/v2/gather";     //MOCK测试

    public static final String CLIENT_KEY = "DEVICE-AES000001";
    @Test
    public void runTest(){
        String trans_id =  new SimpleDateFormat("yyyyMMddHHmmssSSS").format(new Date());
        JSONObject jsonDto = new JSONObject();
//       一级参数匹配
        jsonDto.put("merchantNo", "8000013190");
        jsonDto.put("xyid", "11809151317433850343101");
        jsonDto.put("screenRes", "1440*2408");
        jsonDto.put("unittype", "DUK-AL20");
        jsonDto.put("bios", "DUK");
        jsonDto.put("cpu", "");
        jsonDto.put("androidId", "d0315f608c8f631f");
//       二级参数匹配
        jsonDto.put("devicename", "HWDUKDUK-AL20");
        jsonDto.put("sysVer", "8.0.0");
        jsonDto.put("imei", "863952035983780,863952035983780");
        jsonDto.put("phonenum", "18637002608");
        jsonDto.put("imsi", "460017013628299,89860117801451167045");
        jsonDto.put("timezone", "GMT+08:00,Asia/Shanghai");
        jsonDto.put("systemlan", "zh");
        jsonDto.put("isroot", "0");
        jsonDto.put("fontnum", "0");
        jsonDto.put("isVirtualApp", "1");
        jsonDto.put("screenres", "1081*2040");
        jsonDto.put("fcpu", "1844000");
        jsonDto.put("totalSize", "121460637696");
        jsonDto.put("mac", "70:8A:09:94:8A:C6");
        jsonDto.put("extra", "TEST12312");
        jsonDto.put("sdSize", "123123123");
        jsonDto.put("romSize", "123123123");
        jsonDto.put("ramSize", "123123123");
        jsonDto.put("sdkVersion", "1.0.3");
        jsonDto.put("appName", "漫生活2223");
        jsonDto.put("location", "777777,777777");
        jsonDto.put("virtualInfo", "{\"ro.product.brand\":\"HONOR\",\"baseBand\":\"678\",\"ro.product.device\":\"HWBND-H\",\"ro.product.manufacturer\":\"HUAWEI\",\"ro.hardware\":\"hi6250\",\"ro.product.model\":\"BND-AL10\",\"ro.build.product\":\"hi6250\",\"ro.build.fingerprint\":\"HONOR/BND-AL10/HWBND-H:7.0/HONORBND-AL10/C00B201:user/release-keys\"}");
        List<String> stringList = new ArrayList<String>();
        stringList.add("zh");
        stringList.add("nus");
        stringList.add("hi");
        stringList.add("so");
        stringList.add("ro");
        stringList.add("in");
        stringList.add("sn");
        stringList.add("sw");
        stringList.add("es");
        stringList.add("dyo");
        stringList.add("ru");
        stringList.add("en");
        stringList.add("zu");
        stringList.add("pt");
        stringList.add("ar");
        stringList.add("ksf");
        stringList.add("ewo");
        stringList.add("rof");
        stringList.add("fr");
        stringList.add("ta");
        stringList.add("mgh");
        stringList.add("fy");
        stringList.add("mgo");
        stringList.add("to");
        stringList.add("qu");
        stringList.add("jmc");
        stringList.add("rw");
        stringList.add("gv");
        stringList.add("chr");
        stringList.add("sv");
        stringList.add("pa");
        stringList.add("cgg");
        stringList.add("dje");
        stringList.add("ksh");
        stringList.add("si");
        stringList.add("luy");
        stringList.add("tr");
        stringList.add("dua");
        stringList.add("nb");
        stringList.add("sr");
        stringList.add("luo");
        stringList.add("ff");
        stringList.add("om");
        stringList.add("cs");
        stringList.add("bs");
        stringList.add("sl");
        stringList.add("uz");
        stringList.add("az");
        stringList.add("ksb");
        stringList.add("vun");
        stringList.add("dav");
        stringList.add("nmg");
        stringList.add("fo");
        stringList.add("el");
        stringList.add("mt");
        stringList.add("ha");
        stringList.add("mas");
        stringList.add("ca");
        stringList.add("ses");
        stringList.add("it");
        stringList.add("ji");
        stringList.add("hr");
        stringList.add("ka");
        stringList.add("nl");
        stringList.add("smn");
        stringList.add("km");
        stringList.add("ee");
        stringList.add("twq");
        stringList.add("eo");
        stringList.add("ne");
        stringList.add("as");
        stringList.add("vi");
        stringList.add("de");
        stringList.add("ig");
        stringList.add("or");
        stringList.add("mua");
        stringList.add("pl");
        stringList.add("lv");
        stringList.add("lb");
        stringList.add("tzm");
        stringList.add("haw");
        stringList.add("shi");
        stringList.add("mn");
        stringList.add("gsw");
        stringList.add("lo");
        stringList.add("kl");
        stringList.add("nnh");
        stringList.add("bo");
        stringList.add("teo");
        stringList.add("et");
        stringList.add("br");
        stringList.add("yo");
        stringList.add("bem");
        stringList.add("ti");
        stringList.add("hu");
        stringList.add("mk");
        stringList.add("sk");
        stringList.add("nyn");
        stringList.add("fa");
        stringList.add("zgh");
        stringList.add("rm");
        stringList.add("wae");
        stringList.add("kok");
        stringList.add("te");
        stringList.add("sq");
        stringList.add("lag");
        stringList.add("da");
        stringList.add("ms");
        stringList.add("ps");
        stringList.add("lt");
        stringList.add("bm");
        stringList.add("kk");
        stringList.add("ln");
        stringList.add("asa");
        stringList.add("dz");
        stringList.add("rn");
        stringList.add("ebu");
        stringList.add("my");
        stringList.add("ak");
        stringList.add("cy");
        stringList.add("vai");
        stringList.add("ce");
        stringList.add("af");
        stringList.add("bn");
        stringList.add("ks");
        stringList.add("bg");
        stringList.add("sah");
        stringList.add("dsb");
        stringList.add("bas");
        stringList.add("nd");
        stringList.add("uk");
        stringList.add("se");
        stringList.add("brx");
        stringList.add("am");
        stringList.add("th");
        stringList.add("ky");
        stringList.add("ur");
        stringList.add("gu");
        stringList.add("ki");
        stringList.add("ja");
        stringList.add("kde");
        stringList.add("ga");
        stringList.add("mer");
        stringList.add("rwk");
        stringList.add("kw");
        stringList.add("mfe");
        stringList.add("mr");
        stringList.add("mg");
        stringList.add("fur");
        stringList.add("ml");
        stringList.add("hy");
        stringList.add("kn");
        stringList.add("sbp");
        stringList.add("ii");
        stringList.add("eu");
        stringList.add("gl");
        stringList.add("kam");
        stringList.add("xog");
        stringList.add("is");
        stringList.add("saq");
        stringList.add("iw");
        stringList.add("nn");
        stringList.add("gd");
        stringList.add("kln");
        stringList.add("be");
        stringList.add("jgo");
        stringList.add("agq");
        stringList.add("os");
        stringList.add("fil");
        stringList.add("lrc");
        stringList.add("yav");
        stringList.add("lu");
        stringList.add("ug");
        stringList.add("seh");
        stringList.add("naq");
        stringList.add("lg");
        stringList.add("lkt");
        stringList.add("sg");
        stringList.add("hsb");
        stringList.add("guz");
        stringList.add("ko");
        stringList.add("kab");
        stringList.add("khq");
        stringList.add("kea");
        stringList.add("bez");
        stringList.add("fi");
        stringList.add("mzn");
        stringList.add("kkj");
        List<String> list = new ArrayList<String>();
//        for (int i = 0; i < 200; i++) {
        list.add("com.huawei.hifolder");
        list.add("com.ali.money.shield");
        list.add("com.huawei.camera");
        list.add("so.ofo.labofo");
        list.add("com.huawei.android.tips");
        list.add("com.google.android.ext.services");
        list.add("com.huawei.synergy");
        list.add("com.huawei.android.launcher");
        list.add("cn.com.shbank.mper");
        list.add("com.midea.ai.appliances");
        list.add("com.huawei.android.UEInfoCheck");
        list.add("com.huawei.health");
        list.add("com.huawei.hidisk");
        list.add("com.huawei.hiview");
        list.add("com.iev.charge");
        list.add("com.huawei.iaware");
        list.add("com.huawei.bluetooth");
        list.add("com.tencent.tmgp.pubgm");
        list.add("com.tencent.tmgp.sgame");
        list.add("com.huawei.android.thememanager");
        list.add("com.huawei.android.chr");
        list.add("com.huawei.android.hsf");
        list.add("com.qiyi.video");
        list.add("com.google.android.onetimeinitializer");
        list.add("com.google.android.ext.shared");
        list.add("com.huawei.nearby");
        list.add("com.huawei.android.FloatTasks");
        list.add("alicom.palm.android");
        list.add("com.tmri.app.main");
        list.add("com.sankuai.meituan");
        list.add("com.huawei.desktop.systemui");
        list.add("com.youku.phone");
        list.add("com.cgbchina.xpt");
        list.add("com.huawei.intelligent");
        list.add("com.huawei.motionservice");
        list.add("org.simalliance.openmobileapi.service");
        list.add("com.huawei.appmarket");
        list.add("com.huawei.recsys");
        list.add("com.tencent.qqmusic");
        list.add("com.sinovatech.unicom.ui");
        list.add("com.huawei.parentcontrol");
        list.add("com.huawei.secime");
        list.add("com.hexin.plat.android");
        list.add("com.qq.ac.android");
        list.add("com.huawei.regservice");
        list.add("com.huawei.vdrive");
        list.add("com.iflytek.speechsuite");
        list.add("com.huawei.wallet");
        list.add("com.huawei.android.totemweather");
        list.add("com.xinyan.personal");
        list.add("com.dianping.v1");
        list.add("com.huawei.cryptosms.service");
        list.add("com.huawei.android.findmyphone");
        list.add("com.huawei.trustcircle");
        list.add("cmb.pb");
        list.add("com.realvnc.android.remote");
        list.add("com.huawei.phoneservice");
        list.add("com.huawei.desktop.explorer");
        list.add("com.huawei.screenrecorder");
        list.add("com.MobileTicket");
        list.add("com.huawei.livewallpaper.ripplestone");
        list.add("com.huawei.videoeditor");
        list.add("com.huawei.securitymgr");
        list.add("com.duowan.mobile");
        list.add("com.google.android.configupdater");
        list.add("com.huawei.iconnect");
        list.add("com.huawei.android.AutoRegSms");
        list.add("com.huawei.KoBackup");
        list.add("com.baofoo.manshenghuo");
        list.add("com.huawei.hiviewtunnel");
        list.add("me.ele");
        list.add("com.huawei.livewallpaper.artflower");
        list.add("in.zhaoj.shadowsocksr");
        list.add("com.huawei.smarthome");
        list.add("com.huawei.vrinstaller");
        list.add("com.ifeng.news2");
        list.add("androidhwext");
        list.add("com.tencent.mm");
        list.add("com.baidu.input_huawei");
        list.add("com.baosight.carsharing");
        list.add("com.stupeflix.replay");
        list.add("com.sankuai.meituan.takeoutnew");
        list.add("huawei.android.widget");
        list.add("com.google.android.marvin.talkback");
        list.add("com.sdu.didi.psnger");
        list.add("com.saike.android.mongo");
        list.add("android");
        list.add("com.tencent.android.qqdownloader");
        list.add("com.pingan.paces.ccms");
        list.add("com.huawei.imedia.sws");
        list.add("com.huawei.bone");
        list.add("com.huawei.fans");
        list.add("com.huawei.hwid");
        list.add("com.huawei.tips");
        list.add("com.huawei.contentsensor");
        list.add("com.huawei.systemserver");
        list.add("com.app.shanghai.metro");
        list.add("com.tencent.qqpim");
        list.add("com.wbxm.icartoon");
        list.add("mobi.w3studio.apps.android.shsmy.phone");
        list.add("com.huawei.android.instantshare");
        list.add("com.huawei.indexsearch.observer");
        list.add("com.taobao.movie.android");
        list.add("com.huawei.trustagent");
        list.add("com.huawei.trustspace");
        list.add("com.huawei.indexsearch");
        list.add("com.huawei.android.internal.app");
        list.add("com.huawei.gamebox");
        list.add("com.huawei.hwasm");
        list.add("com.huawei.lives");
        list.add("com.huawei.wifiprobqeservice");
        list.add("com.wanbangauto.chargepile");
        list.add("com.inke.trivia");
        list.add("cn.com.gjzq.yjb2");
        list.add("com.huawei.systemmanager");
        list.add("com.tencent.qqlive");
        list.add("com.huawei.yellowpage");
        list.add("com.dynamicode.BaoFoo.mobileToken");
        list.add("com.hicloud.android.clone");
        list.add("com.xinyan.android.device.xinyandevicedemo");
        list.add("com.huawei.hilink.framework");
        list.add("com.taobao.mobile.dipei");
        list.add("com.google.android.webview");
        list.add("com.beisen.italent");
        list.add("com.huawei.HwMultiScreenShot");
        list.add("com.huawei.decision");
        list.add("com.huawei.vassistant");
        list.add("com.didapinche.booking");
        list.add("com.google.android.syncadapters.contacts");
        list.add("com.cloudpower.netsale.activity");
        list.add("com.mercury.mercuryrouter");
        list.add("com.example.android.notepad");
        list.add("com.youdao.note");
        list.add("com.microsoft.translator");
        list.add("com.hexin.zhanghu");
        list.add("org.zxq.teleri");
        list.add("com.netease.zjz.huawei");
        list.add("com.ss.android.ugc.aweme");
        list.add("com.huawei.watch.sync");
        list.add("com.sohu.sohuvideo");
        list.add("com.google.android.gms");
        list.add("com.google.android.gsf");
        list.add("com.huawei.hwstartupguide");
        list.add("com.vyou.vcameraclient");
        list.add("com.google.android.partnersetup");
        list.add("com.tencent.mobileqq");
        list.add("com.huawei.fido.uafclient");
        list.add("com.sf.activity");
        list.add("com.svox.pico");
        list.add("com.huawei.hwireader");
        list.add("com.huawei.android.mirrorshare");
        list.add("com.huawei.contactscamcard");
        list.add("cn.bluerhino.client");
        list.add("com.google.android.printservice.recommendation");
        list.add("com.huawei.android.totemweatherwidget");
        list.add("com.huawei.himovie");
        list.add("com.huawei.hitouch");
        list.add("com.umaman.laiyifen");
        list.add("com.huawei.compass");
        list.add("com.huawei.livewallpaper.flowersbloom");
        list.add("com.huawei.vrservice");
        list.add("com.baidu.BaiduMap");
        list.add("com.huawei.android.dsdscardmanager");
        list.add("com.eastmoney.android.fund");
        list.add("com.zhihu.android");
        list.add("com.huawei.android.hwaps");
        list.add("com.huawei.android.hwouc");
        list.add("com.huawei.android.hwpay");
        list.add("com.tuniu.app.ui");
        list.add("com.huawei.android.wfdft");
        list.add("com.amap.android.ams");
        list.add("com.huawei.mmitest");
        list.add("com.chinamworld.main");
        list.add("com.huawei.powergenie");
        list.add("cn.eclicks.wzsearch");
        list.add("com.qeexo.smartshot");
        list.add("com.xinyan.credit");
        list.add("com.google.android.backuptransport");
        list.add("com.tencent.news");
        list.add("com.huawei.android.instantonline");
        list.add("com.netease.mail");
        list.add("com.jingdong.app.mall");
        list.add("com.vmall.client");
        list.add("com.autonavi.minimap");
        list.add("com.huawei.android.projectmenu");
        list.add("com.binance.dev");
        list.add("com.taobao.idlefish");
        list.add("com.huawei.android.totemweatherapp");
        list.add("ctrip.android.view");
        list.add("cn.xq.shareelb");
        list.add("com.huawei.android.remotecontroller");
        list.add("com.anyoee.charge.app");
        list.add("com.pa.health");
        list.add("com.huawei.android.pushagent");
        list.add("com.huawei.livewallpaper.mountaincloud");
        list.add("com.yiwang");
        list.add("com.huawei.livewallpaper.naturalgarden");
        list.add("com.sina.weibo");
        list.add("com.gift.android");
        list.add("com.huawei.scanner");
        list.add("com.tencent.tmgp.pubgmhd");
        list.add("com.meituan.qcs.r.android");
        list.add("pro.huobi");
        list.add("com.mybank.android.phone");
        list.add("com.yongche.android");
        list.add("com.huawei.hwdetectrepair");
        list.add("com.baidu.netdisk");
        list.add("com.tplink.cloudrouter");
        list.add("com.huawei.hwusbearphoneupdate");
        list.add("com.huawei.android.karaoke");
        list.add("com.jtjr99.jiayoubao");
        list.add("com.taobao.taobao");
        list.add("com.harvestfund2");
        list.add("com.huawei.bd");
        list.add("com.huawei.ca");
        list.add("com.huawei.skytone");
        list.add("com.cmbchina.ccd.pluto.cmbActivity");
        list.add("com.huawei.hiskytone");
        list.add("com.huawei.aod");
        list.add("com.huawei.ims");
        list.add("com.huawei.lbs");
        list.add("com.huawei.nlp");
        list.add("com.comic.manhuatai");
        list.add("com.huawei.hiaction");
        list.add("com.eg.android.AlipayGphone");
        list.add("com.huawei.android.airsharing");
        list.add("cn.wps.moffice_eng");
        list.add("com.huawei.rcsserviceapplication");
        list.add("com.taobao.trip");
//        }
        jsonDto.put("languageList",JSONObject.toJSONString(stringList));
        jsonDto.put("softList", compressSoft(list));
        String requestData = jsonDto.toString();
        System.out.println("明文请求：" + jsonDto.toString());
        try{
            requestData = AesUtil.encrypt(requestData, CLIENT_KEY);
        } catch (Exception e){
            e.printStackTrace();
         }
        JSONObject jsonDto1 = new JSONObject();
        jsonDto1.put("message", requestData);
        System.out.println("加密报文：" + jsonDto1.toString());


        try {
            ApiPostUtil postUtil = new ApiPostUtil(url,10000,10000);
            String responseData = postUtil.sendHttps(jsonDto1.toJSONString(),"POST","UTF-8");
//            String responseData = HttpRequestUtil.sendHttpPost1(url, jsonDto1.toString()).toString();
            System.out.println("返回结果密文：" + new String(responseData.getBytes(), "UTF-8"));
         } catch (Exception e){
            e.printStackTrace();
        }
    }
    /*压缩软件列表信息*/
    private byte[] compressSoft(List<String> list){
        String softList =   JSONObject.toJSONString(list);
        try {
            byte[] mByte = GzipUtils.compress(softList.getBytes());
            return mByte;
        } catch (Exception e){
            e.printStackTrace();
            System.out.println("zip error:" + e.getCause() + e.getMessage());
        }
        return null;
    }
}